import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import { HEADER_ITEMS, LOGO } from "@/config/constants";
import { CustomText } from "@/components/ui/title";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import CustomHeader from "@/components/layouts/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <CustomHeader />
        {children}
      </body>
    </html>
  );
}
