import type { Metadata } from "next";
import "./globals.css";

import CustomHeader from "@/components/layouts/header";
import { Toaster } from "@/components/ui/sonner";
import Fotter from "@/components/layouts/fotter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <CustomHeader />
        {children}
        <Fotter />
        <Toaster />
      </body>
    </html>
  );
}
